springfoundation:
  db:
    url: jdbc:h2:mem:springfoundation
    username: h2
    password: h2
    driverClassName: org.h2.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: H2